export function exportSummaryAsWord(title, summary) {
  const isRtl = /[֐-׿]/.test(summary)
  const dir = isRtl ? 'rtl' : 'ltr'
  const align = isRtl ? 'right' : 'left'

  // Convert markdown-style headings and bold to HTML
  const htmlBody = summary
    .split('\n')
    .map((line) => {
      if (line.startsWith('## ')) {
        return `<h2>${line.slice(3)}</h2>`
      }
      if (line.startsWith('# ')) {
        return `<h1>${line.slice(2)}</h1>`
      }
      // Bold: **text**
      const withBold = line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      // Bullet points
      if (withBold.trimStart().startsWith('•')) {
        return `<p style="margin:4pt 0;">${withBold}</p>`
      }
      if (withBold.trim() === '') return '<br/>'
      return `<p>${withBold}</p>`
    })
    .join('\n')

  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8"/>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 12pt;
      direction: ${dir};
      text-align: ${align};
      margin: 2cm;
      color: #1a1a1a;
    }
    h1 { font-size: 18pt; color: #2c3e50; margin-top: 0; }
    h2 { font-size: 14pt; color: #34495e; margin-top: 18pt; margin-bottom: 6pt; border-bottom: 1px solid #bdc3c7; padding-bottom: 3pt; }
    p  { line-height: 1.6; margin: 6pt 0; }
    strong { color: #2c3e50; }
    .meta { color: #7f8c8d; font-size: 10pt; margin-bottom: 18pt; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">${isRtl ? 'סיכום שנוצר על ידי StudyRush AI' : 'Summary generated by StudyRush AI'} · ${new Date().toLocaleDateString(isRtl ? 'he-IL' : 'en-US')}</p>
  ${htmlBody}
</body>
</html>`

  const blob = new Blob(['﻿', html], {
    type: 'application/msword',
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title.replace(/[/\\?%*:|"<>]/g, '-')}.doc`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
